
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 35;
  public static final int MULT = 34;
  public static final int ELSIF = 9;
  public static final int INTEGER = 56;
  public static final int LPAREN = 46;
  public static final int GREATER = 37;
  public static final int ARRAY = 3;
  public static final int LESS = 36;
  public static final int FOR = 12;
  public static final int WRITE = 30;
  public static final int RPAREN = 47;
  public static final int SEMICOLON = 44;
  public static final int NOT = 17;
  public static final int IS = 14;
  public static final int AND = 2;
  public static final int RECORD = 23;
  public static final int TYPE = 27;
  public static final int OR = 19;
  public static final int COMMA = 45;
  public static final int DIV = 6;
  public static final int BEGIN = 4;
  public static final int LOOP = 15;
  public static final int EXIT = 11;
  public static final int LBRKT = 50;
  public static final int LESSEQ = 39;
  public static final int ASSIGN = 38;
  public static final int IF = 13;
  public static final int ID = 54;
  public static final int DOT = 31;
  public static final int OF = 18;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int NUMERIC_CONSTANT = 58;
  public static final int EQUAL = 41;
  public static final int BY = 5;
  public static final int error = 1;
  public static final int PROGRAM = 21;
  public static final int ADD = 33;
  public static final int MOD = 16;
  public static final int LSQBKTLESS = 52;
  public static final int REAL = 57;
  public static final int COLON = 43;
  public static final int ELSE = 8;
  public static final int READ = 22;
  public static final int TO = 26;
  public static final int LSQBKT = 48;
  public static final int WHILE = 29;
  public static final int RBRKT = 51;
  public static final int GREATERRSQBKT = 53;
  public static final int THEN = 25;
  public static final int END = 10;
  public static final int STRING = 55;
  public static final int RSQBKT = 49;
  public static final int GREATEREQ = 40;
  public static final int DIFF = 42;
  public static final int SUB = 32;
  public static final int VAR = 28;
  public static final int PROCEDURE = 20;
  public static final int DO = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "ARRAY",
  "BEGIN",
  "BY",
  "DIV",
  "DO",
  "ELSE",
  "ELSIF",
  "END",
  "EXIT",
  "FOR",
  "IF",
  "IS",
  "LOOP",
  "MOD",
  "NOT",
  "OF",
  "OR",
  "PROCEDURE",
  "PROGRAM",
  "READ",
  "RECORD",
  "RETURN",
  "THEN",
  "TO",
  "TYPE",
  "VAR",
  "WHILE",
  "WRITE",
  "DOT",
  "SUB",
  "ADD",
  "MULT",
  "DIVIDE",
  "LESS",
  "GREATER",
  "ASSIGN",
  "LESSEQ",
  "GREATEREQ",
  "EQUAL",
  "DIFF",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LSQBKT",
  "RSQBKT",
  "LBRKT",
  "RBRKT",
  "LSQBKTLESS",
  "GREATERRSQBKT",
  "ID",
  "STRING",
  "INTEGER",
  "REAL",
  "NUMERIC_CONSTANT"
  };
}

